import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import FloatingChatWidget from "@/components/FloatingChatWidget";
import GoogleTranslate from "@/components/GoogleTranslate"; // ✅ Import this
import MarathiVoiceover from "@/components/marathiVoiceover";
import EventNotifier from "../components/EventNotifier"; // Add this import
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link
            href="https://fonts.googleapis.com/css2?family=Noto+Sans+Devanagari&display=swap"
            rel="stylesheet"
          />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <GoogleTranslate /> {/* ✅ Client-only component */}
          <MarathiVoiceover />
          {children}
          <EventNotifier /> {/* Add this line */}
          <ToastContainer 
            position="top-right" 
            autoClose={8000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
          />
          <FloatingChatWidget />
        </body>
      </html>
    </ClerkProvider>
  );
}
